Move default gbp.conf back to the right location
0.8.9 placed gbp.conf at /etc/git-buildpackage/gbp.conf/gbp.conf. Move
the file back to the correct location.

Closes: #850937
Thanks: Luca Boccassi

diff --git a/debian/git-buildpackage.preinst b/debian/git-buildpackage.preinst
--- a/debian/git-buildpackage.preinst
+++ b/debian/git-buildpackage.preinst
@@ -13,11 +13,26 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+cleanup_misplaced()
+{
+    ver=$1
+    misplaced=/etc/git-buildpackage/gbp.conf/gbp.conf
+    gbp_conf=/etc/git-buildpackage/gbp.conf
+    if [ -f "${misplaced}" ] && [ "$ver" = "0.8.9" ]; then
+        mv -f "${misplaced}" "${gbp_conf}.dpkg-bak"
+        if ! rmdir "${gbp_conf}"; then
+            echo "Cannot remove bad dir ${gbp_conf}, trying rename" 1>&2
+            mv -f "${gbp_conf}" "${gbp_conf}".dpkg-dir-bak
+        fi
+        mv -f ${gbp_conf}.dpkg-bak ${gbp_conf}
+    fi
+}
 
 case "$1" in
     install|upgrade)
         dpkg-maintscript-helper rm_conffile \
             /etc/bash_completion.d/git-buildpackage 0.6.34~ git-buildpackage -- "$@"
+        cleanup_misplaced $2
     ;;
 
     abort-upgrade)
